app:
  name: dms-server
server:
  port: 8081
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.27.44.76:1433;databaseName=mhFactory_db
    username: sa
    password: NS2$0lution
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        show_sql: true
        generate_statistics: true
logging:
  file:
    path: 'd:/nse/log/dms.%d{yyyy-MM-dd}.%i'
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  header: Authorization
  secret: VABoAGkAcwAgAGkAcwAgAEQATQBTACAAUwBlAGMAcgBlAHQAIABLAGUAeQAuACAAZgBvAHIAIABKAHMAbwBuAFcAZQBiAFQAbwBrAGUAbgAgAA==
  token-validity-seconds: 86400
