app:
  name: dms-api-server
  api:
    version:  0.0.1
    description: NSE DMS API SERVER
    swagger:
      enable: true
server:
  port: 8081
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ENC(E/mZMgRdnogTcWh3jnAoysONRGbE/KujMQcqljbgiynW7HecgvZJSlnILM86H2LtKgXssCn3a8WjEDHj/ysliEMvsBWfbMlY)
    username: ENC(3EXbWYCL/VsplYv7qCveWw==)
    password: ENC(7wgLzOE9+lXX7gRVX40n9WwN6FMtOSFy)
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        show_sql: true
        generate_statistics: true
  cache:
    ehcache:
      config: classpath:/com.dms/config/cache/DmsEhCache.xml
logging:
  file:
    path: 'd:/nse/log/dms.%d{yyyy-MM-dd}.%i'
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  header: Authorization
  secret: VABoAGkAcwAgAGkAcwAgAEQATQBTACAAUwBlAGMAcgBlAHQAIABLAGUAeQAuACAAZgBvAHIAIABKAHMAbwBuAFcAZQBiAFQAbwBrAGUAbgAgAA==
  token-validity-seconds: 86400
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: NseDmsApiServerJasyptKey
